name: Deploy to VPS

on:
  push:
    branches:
      - main  # अगर आपकी ब्रांच का नाम 'master' है तो इसे बदल लें

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        env:
          # GitHub Secrets से ENV डेटा को एक वेरिएबल में ले रहे हैं
          ENV_DATA: ${{ secrets.ENV_FILE_CONTENT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ENV_DATA
          script: |
            # आपके प्रोजेक्ट फोल्डर में जाना
            cd waste-mng
            
            # नया कोड पुल करना
            git pull origin main
            
            # पुरानी .env फाइल को डिलीट करके (अगर है) नई फाइल क्रिएट करना
            # ENV_DATA में जो भी हमने GitHub Secret में डाला है, वो यहाँ .env में सेव हो जाएगा
            echo "$ENV_DATA" > .env
            
            # डिपेंडेंसीज इंस्टॉल करना
            npm install --legacy-peer-deps
            
            # प्रोजेक्ट बिल्ड करना (इस समय .env फाइल मौजूद है, तो नेक्स्ट इसे रीड कर लेगा)
            npm run build
            
            # PM2 से सर्वर रीस्टार्ट करना
            pm2 restart waste-mng